### ISSUE TITLE
Malformed, superfluous or missing files

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-hcp#1]
Ongoing list of superfluous or missing files resulting from `hcp.io.file_mapping.get_s3_keys_meg`

- ~~"noise_subject" and "noise_empty_room" keys are not properly constructed (<- haven't checked this one yet)~~
- "_TIM.mat" is requested for e.g. preprocessed "StoryM", but only exists for "WM"
- ~~?? I somehow didn't get "mri/T1.mgz" first time around~~
- ~~`hcp.workflows.anatomy.make_mne_anatomy(..., mode='minial')` requests e.g. labels, but `hcp.io.file_mapping.get_s3_keys_anatomy(subj, mode="minimal")` does not return labels~~
- ...

**Comment by jona-sassenhagen** [comment]
I am not sure if this user error or a bug? ..
```
hcp.workflows.anatomy.make_mne_anatomy(
    subject='100307', hcp_path=home_f,
    anatomy_path=anatomy_path,
    recordings_path=recordings_path,
    mode='minimal')

FileNotFoundError: [Errno 2] No such file or directory: '/home/jona/experiments/hcp/HCP_900/100307/T1w/100307/mri/T1.mgz' -> '/home/jona/experiments/hcp/mne_anatomy/100307/100307/T1w/100307/mri/T1.mgz'
```

Note double subject code in target file.

**Comment by dengemann** [comment]
Thanks Jona, that's very useful feedback. In the meantime I pushed a couple of fixes to annotations-reading and also started writing unit tests, so far with local files (not for travis). Will work through this soon.

**Comment by dengemann** [comment]
> I am not sure if this user error or a bug? ..

not sure I understand this one, works on my machines ... you have to make sure that all directories and files exist prior to running the anatomy workflow.

**Comment by jona-sassenhagen** [comment]
Thanks for fixes, downloading is much improved. I will try to run more tests.

>not sure I understand this one, works on my machines ... you have to make sure that all directories and files exist prior to running the anatomy workflow.

Well they do .. consider:

`/home/jona/experiments/hcp/HCP_900/102816/T1w/102816/mri/T1.mgz` exists.

```
import hcp
import os
home = os.path.expanduser("~")
home += "/experiments/hcp/"

home_f = home + "HCP_900/"

anatomy_path = home + "anatomy_path"
recordings_path = home + "recordings_path"

hcp.workflows.anatomy.make_mne_anatomy(
    subject=subj, hcp_path=home_f,
    anatomy_path=anatomy_path,
    recordings_path=recordings_path,
    mode='minimal')
```
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/jona/experiments/hcp/HCP_900/102816/T1w/102816/mri/T1.mgz' -> '/home/jona/experiments/hcp/anatomy_path/102816/102816/T1w/102816/mri/T1.mgz'
```

What's with the second file path ('/home/jona/experiments/hcp/anatomy_path/102816/102816/T1w/102816/mri/T1.mgz')?
It seems wrong.

`/home/jona/experiments/hcp/anatomy_path/102816/` exists after running the command btw, with the contents 'mri' and 'label'.

**Comment by dengemann** [comment]
I'm not sure I understand what's happening. This function should:

1. download data into hcp_path
2. expand stuff, do mne-hcp magic and write some results into anatomy_path, the thing that is referenced as "SUBJECTS_DIR".

>/home/jona/experiments/hcp/anatomy_path/102816/ exists after running the command btw, with the contents 'mri' and 'label'.

maybe there is an issue with linking that is platform dependent, the way the code behaves is that it downloads stuff to hcp_path and then links in order to avoid copies on the hard drive.
but that's also surprising as I have tried this on both Mac and Linux.

**Comment by jona-sassenhagen** [comment]
I will investigate ... this is on Ubuntu though.

But, do you mean 'download'? I thought it only acts on files I've already downloaded?

**Comment by dengemann** [comment]
Yes, sorry, it assumes that you have downloaded the files as returned by
the s3 functions in file_mapping into the hcp_path. Can you give more
detail about tracebacks? Which is the crashing line?

**Comment by jona-sassenhagen** [comment]
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-b98e47867a61> in <module>()
     13     anatomy_path=anatomy_path,
     14     recordings_path=recordings_path,
---> 15     mode='minimal') # consider "minimal" for linking and writing less 

/home/jona/anaconda3/lib/python3.5/site-packages/hcp-0.1.dev0-py3.5.egg/hcp/workflows/anatomy.py in make_mne_anatomy(subject, anatomy_path, recordings_path, hcp_path, mode, outputs)
     80                 this_anatomy_path, source.split(split_path)[-1])
     81             if not op.exists(target):
---> 82                 os.symlink(source, target)
     83 
     84     logger.info('reading extended structural processing ...')

FileNotFoundError: [Errno 2] No such file or directory: '/home/jona/experiments/hcp/HCP_900/102816/T1w/102816/mri/T1.mgz' -> '/home/jona/experiments/hcp/anatomy_path/102816/102816/T1w/102816/mri/T1.mgz'
```

**Comment by dengemann** [comment]
Ah ok, so "target" seems to have problem ... on your machine. Maybe the
target formation based on splitting behaves in an operating system
dependent way. We need to figure out what goes wrong there, why there are 2
subsequent subject folders.

**Comment by jona-sassenhagen** [comment]
For this:

```
for source in files:
    split_path = '/' + op.join(*source.split('/')[:6]) + '/'
    target = op.join(
        this_anatomy_path, source.split(split_path)[-1])
```

I get this:

```
source
Out[23]:
'/home/jona/experiments/hcp/HCP_900/102816/T1w/102816/mri/T1.mgz'
In [24]:

split_path
Out[24]:
'/home/jona/experiments/hcp/HCP_900/'
In [25]:

this_anatomy_path
Out[25]:
'/home/jona/experiments/hcp/anatomy_path/102816'
In [26]:

source.split(split_path)[-1]
Out[26]:
'102816/T1w/102816/mri/T1.mgz'
```

**Comment by dengemann** [comment]
Ok cool, then we know where the bug comes from... Maybe its a python 2-3
thing. Will try to look tomorrow.

**Comment by jona-sassenhagen** [comment]
I just checked it on py27 and get the same result there.

**Comment by jona-sassenhagen** [comment]
Works now!

**Comment by dengemann** [comment]
Can we close this issue then or are there other things unsolved?

**Comment by jona-sassenhagen** [comment]
Only one thing missing from what I can tell: _TIM is still requested for the story, even though StoryM only has _RESP.

**Comment by dengemann** [comment]
Ahh. Wanna fix it? I can take a look this afternoon.

**Comment by jona-sassenhagen** [comment]
I can try later ...

**Comment by jona-sassenhagen** [comment]
Yup, it's fixed now, thanks!
