### ISSUE TITLE
issue with coordinate system

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-hcp#11]
This is partially related to https://github.com/mne-tools/mne-python/issues/3411

Me and @jaeilepp discovered that the legend for spatial colors is rotated due to the fact that `convert` is set to `False` here:
https://github.com/mne-tools/mne-hcp/blob/master/hcp/io/read.py#L86-88

Further, we noticed that setting the `rename_channels=True` (default) also means that we don't need a new layout file for the spatial colors

Is there a particular reason for these choices? If not, I can make a PR to fix it ...

**Comment by jaeilepp** [comment]
> legend for spatial colors is rotated 

And in fact the channel positions in info are rotated.

**Comment by dengemann** [comment]
It has to be false, else everything else breaks. See in preprocessing the
sensor conversion function. It is essentially a problem of mne that it does
not allow native bti sensor maps for plotting.

**Comment by dengemann** [comment]
> Is there a particular reason for these choices? If not, I can make a PR to fix it ...

these are *absolutely crucial* to be clear. We need to process everything in native BTI coordinates, other wise the coregistration information will not work. 

see https://github.com/mne-tools/mne-hcp/blob/master/hcp/preprocessing.py#L152

and https://github.com/mne-tools/mne-hcp/blob/master/hcp/preprocessing.py#L63

to deal with this.

**Comment by dengemann** [comment]
And some background, all these options that you see in the MNE code were added precisely to make mne-hcp possible.

This should be better documented to avoid repeated questions of this kind. I am not sure where at this point thought. Maybe in the readme, if there is not already a comment on this.

**Comment by dengemann** [comment]
Can we close this?

**Comment by jasmainak** [comment]
yep, let's do that

**Comment by jona-sassenhagen** [comment]
So just so I get this clear, the solution would have to be on the MNE viz side (allowing BTI plots)?

@jaeilepp @jasmainak is either of you on this?

**Comment by jasmainak** [comment]
This did it for me:
```py
    for ch in raw.info['chs']:
        x, y, z = ch['loc'][:3]
        ch['loc'][:3] = -y, x, z
```
Basically, you use the rotated coordinates for spatial colors but if you want to do source loc, you don't rotate the channel locations.

**Comment by jona-sassenhagen** [comment]
Seems like a hack :) But could we hack it into the MNE plotting functions?

**Comment by jasmainak** [comment]
I think yes, if you can detect in MNE if it's the original coordinate system or the converted one. @dengemann explained to me that the units in `info` might offer a clue (millimeter or not).
