### ISSUE TITLE
error loading epochs

### ISSUE THREAD

**Issue by MadsJensen** [mne-tools/mne-hcp#12]
Hi 

I am having an issue trying to load epochs with the read_epochs function. It is the master branch from mne-hcp and mne-python

```python
params = dict(
    subject='******',
    data_type='task_motor')
epochs = hcp.io.read_epochs_hcp(**params)
```

It gives the following command. 

```python
command "mne_create_comp_data" to include weights as printed out by the 4D "print_table" routine.
Traceback (most recent call last):

  File "<ipython-input-14-78fc6c153329>", line 24, in <module>
    epochs = hcp.io.read_epochs_hcp(**params) # ...

  File "/Users/au194693/anaconda/lib/python2.7/site-packages/hcp-0.1.dev0-py2.7.egg/hcp/io/read.py", line 242, in read_epochs_hcp
    epochs = _read_epochs(epochs_mat_fname=epochs_mat_fname, info=info)

  File "/Users/au194693/anaconda/lib/python2.7/site-packages/hcp-0.1.dev0-py2.7.egg/hcp/io/read.py", line 253, in _read_epochs
    data = np.array([data['trial'].tolist()][0].tolist())

ValueError: could not broadcast input array from shape (250,1221) into shape (250)
```

best,
mads

**Comment by dengemann** [comment]
Hi this maybe a problem with downloaded files that can be corrupted if internet connection is bad. To be sure can you reproduce it with another subject?

**Comment by MadsJensen** [comment]
Hi, I have tried different subject, I can provide the ids but I am not sure about the policy regarding that, and on both a linux system and osx and I get the same error.

**Comment by dengemann** [comment]
@MadsJensen ok I'll check it out later. If it's appearing across subjects it's rather a bug I assume.

**Comment by MadsJensen** [comment]
@dengemann Thanks!

**Comment by dengemann** [comment]
@MadsJensen sorry for the delay, I'm now looking into it.

**Comment by MadsJensen** [comment]
hi @dengemann I can see there has been some updates to the code, have you managed to fix the problem?

**Comment by dengemann** [comment]
I am writing tests currently, you can expect a lot of changes over the next
days and weeks. Stay tuned. There will also be a release soon and examples.

**Comment by dengemann** [comment]
@MadsJensen I think it is fixed. It was not clear to me so far that HCP ships different epoch lengths, namely regular trials  and fixation periods. I've added a parameter to chose between the two, defaulting  to the regular trials. The new tests pass on my box. See cc37a8ae562f560483371d72fae1134cce434d74 for more details. Let me know if this works for you now.

**Comment by MadsJensen** [comment]
@dengemann it works for me now :) Thanks for looking into it and fixing it.

**Comment by dengemann** [comment]
Also reading evokeds now properly works for motor. Btw. Take a look around,
we have the first examples and tutorials and a documentation with API
reference. At this stage it is easy to integrate contributions :) a travis
CI is getting ready the next days.

**Comment by MadsJensen** [comment]
That sounds good, and I will do.

**Comment by dengemann** [comment]
Great :) Writing a section on the current contributions details later. Now
that we've got Travis CI up and running we can develop as usual.
