### ISSUE TITLE
more info on how to remove artefacts for epochs objects

### ISSUE THREAD

**Issue by JohnGriffiths** [mne-tools/mne-hcp#18]
Hi. 

Is it the case that arterfact rejection with removal of bad channels / epochs and ICA components needs to be done before source localization on the epochs data?

I know you have some pointers in the readme.md, but would it be possible to get a little bit more info on exactly how to use the annotations to reject segments / epochs in the epochs object, and likewise with the ICA components? 

Reason I'm stuck is that it seems all of the MNE documentation on this starts with Raw objects; not with epochs objects. Not sure how to proceed. 

Ta,

john

**Comment by dengemann** [comment]
Hi John,

if you start form the epochs you're already set, there's nothing to do for
the MEG data.
The epochs are preprocessed (bad ICA components subtracted, etc.);
You will need to compute the inverse solution and what else you need.
Hope this helps.

Denis

**Comment by JohnGriffiths** [comment]
Ok great. This was what I had thought, but then was a bit thrown by some comments saying 'bad segments and channels have to be read and used' and 'ICA components related to eye blinks and heart beats need to be removed from the data'. I guess those bits are referring specifically to replicating HCP sensor space analyses (?). 

Thanks for speed reply.

**Comment by dengemann** [comment]
Yes, this is related to reprocessing from scratch. Hope it's clearer now.

**Comment by dengemann** [comment]
@JohnGriffiths have a look now at the repo, we had an unofficial release, the website is up and tests are running on continuous integration, travisCI so far. I'll close this for now. Please feel free to comment, open issues or contribute. We now have a fully fledged dev setup.
