### ISSUE TITLE
API: decide about fate of the workflows modules.

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-hcp#22]
Maybe it will be obsolete once we have examples. I tend to remove these modules since I don't want to make any commitments to maintaining specific pipelines. To me documentation + examples should be the way to go.

Any opinions on this @jasmainak @agramfort ?

**Comment by jasmainak** [comment]
I agree we should probably focus our energies on tests + documentations. It also makes it easier for people to contribute

**Comment by dengemann** [comment]
I think the workflows.inverse can be deleted and demonstrated in an example. the anatomy should simply be moved to hcp namespace. it is a useful basic function for setting up things. This way we don't have to make commitments to the notion of a workflow

**Comment by dengemann** [comment]
Alright, addressed.
