### ISSUE TITLE
API: happy with names (I don't mean the color of the links)

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-hcp#28]
It is a good moment to decide about function names and conventions. Shortly there will be a first official release, then it will be costly to change names and patterns.

Personally I'm mostly happy enough, but I'd like to get some feedback, rather now than later.

cc @agramfort @Eric89GXL @jasmainak

**Comment by agramfort** [comment]
except the pink for the links on the site I am happy :)

kidding pink is great. My daughter loves it :)

**Comment by dengemann** [comment]
@agramfort did you go through the API names and module hierarchies. Now is a good moment to change names and modules and so on. To the contrary, changing bootswap styles does not necessitate a deprecation cycle.

**Comment by dengemann** [comment]
@agramfort: another thing, would you prefer an MNE-Python-consistent css for the HCP website (or will your daughter protest about missing links in pink)?

**Comment by Eric89GXL** [comment]
I think the color difference is nice actually.

**Comment by dengemann** [comment]
Me too :)

**Comment by Eric89GXL** [comment]
API looks reasonable to me. Comments:

1. Add link to the README that points to mne-tools.github.io/mne-hcp
2. The name `map_chs_to_mne` isn't great, I didn't expect it to actually transform sensor coords. Maybe `transform_sensor_coords_to_mne`, even though it's longer
3. `get_s3_keys_meg` and `get_s3_keys_anatomy` have the same initial docstring
4. `read_ica_hcp` has a bad docstring, [renders incorrectly] (http://mne-tools.github.io/mne-hcp/python_reference.html)

**Comment by dengemann** [comment]
> transform_sensor_coords_to_mne, even though it's longer

Maybe `map_ch_coords_to_mne` It is otherwise very mong. Any other ideas?

**Comment by Eric89GXL** [comment]
`map_ch_coords_mne` or `map_ch_coords_to_mne` is fine by me

**Comment by agramfort** [comment]
I can live with pink :)

**Comment by jasmainak** [comment]
pink is the new black :)

**Comment by dengemann** [comment]
> pink is the new black :)

updated title accordingly

**Comment by dengemann** [comment]
cc @jona-sassenhagen happiness

**Comment by jona-sassenhagen** [comment]
Just one really tiny idea: in MNE proper, we use '/' for hierarchical ID. Maybe this could also be used for the data type names, e.g.

`task_working_memory` -> `task/working_memory`
`task_story_math` -> `task/story_math`

`noise_subject` -> `noise/subject`

Might not be worth the effort though.
