### ISSUE TITLE
Output of hcp.preprocessing.transform_sensors_to_mne is very verbose

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-hcp#4]
hcp.preprocessing.transform_sensors_to_mne prints hundreds of lines per run. It is the only place `print` is called in the code ... maybe we can have a verbosity parameter here, or at least tidy it up by collecting all channel names to be converted into a list and only printing "Converting channels A48, A221, A134, ..." etc at the end, instead of spending one line per conversion?

**Comment by dengemann** [comment]
Fine with me. But let's maybe not engineer to heavy for now. Things may change. One thing we can do is using loggers from mne.
