### ISSUE TITLE
BUG: read_epochs onset parameter not passed

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-hcp#47]
Small comment.

Defaults param of `onset` in `hcp.read_epochs` is `'TIM'` which isn't described in the doc.

I guess this is equivalent to "stim"?

**Comment by dengemann** [comment]
>mI guess this is equivalent to "stim"?

It's a revision bug. It should be 'stim' now. Interesting that it works ... PR welcome. Otherwise I can look into it soon.

**Comment by kingjr** [comment]
The parameter onset doesn't seem to be passed actually, you can give `foo` instead without an error

**Comment by dengemann** [comment]
This should not be the case. It should be passed and tested.
